import 'package:sqflite/sqflite.dart';
import 'package:slovingo/services/database_helper.dart';

/// Seeds static content (levels/words/tasks) inside a single transaction.
Future<void> seedSample() async {
  final db = await DatabaseHelper.instance.database;

  await db.transaction((txn) async {
    final now = DateTime.now().toIso8601String();

    // Skip if already seeded to avoid unnecessary work/locks.
    final countResult = await txn.rawQuery('SELECT COUNT(*) FROM levels');
    final alreadySeeded = Sqflite.firstIntValue(countResult) != null && Sqflite.firstIntValue(countResult)! > 0;
    if (alreadySeeded) return;

    // Reset static tables.
    await txn.delete('levels');
    await txn.delete('words');
    await txn.delete('lesson_tasks');

    final levels = [
      // Starter (1 lesson)
      {
        'id': 'starter_1',
        'levelNumber': 1,
        'title': 'Everyday basics',
        'description': 'Starter',
        'levelCategory': 'lesson',
        'isLocked': 0,
        'wordIds': 'w1,w2,w3,w4,w5',
        'requiredScore': 70,
        'createdAt': now,
        'updatedAt': now,
      },
      // Beginner (functional)
      {
        'id': 'beginner_1',
        'levelNumber': 2,
        'title': 'Greetings & phrases',
        'description': 'Beginner',
        'levelCategory': 'lesson',
        'isLocked': 1,
        'wordIds': 'w6,w7,w8,w9',
        'requiredScore': 70,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'beginner_2',
        'levelNumber': 3,
        'title': 'People & family',
        'description': 'Beginner',
        'levelCategory': 'lesson',
        'isLocked': 1,
        'wordIds': 'w10,w11,w12,w13',
        'requiredScore': 70,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'beginner_3',
        'levelNumber': 4,
        'title': 'Food & drink',
        'description': 'Beginner',
        'levelCategory': 'lesson',
        'isLocked': 1,
        'wordIds': 'w14,w15,w16,w17',
        'requiredScore': 70,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'beginner_test',
        'levelNumber': 5,
        'title': 'Beginner test',
        'description': 'Beginner',
        'levelCategory': 'test',
        'isLocked': 1,
        'wordIds': '',
        'requiredScore': 70,
        'createdAt': now,
        'updatedAt': now,
      },
      // Intermediate (placeholder)
      {
        'id': 'intermediate_1',
        'levelNumber': 6,
        'title': 'Intermediate 1',
        'description': 'Intermediate',
        'levelCategory': 'lesson',
        'isLocked': 1,
        'wordIds': '',
        'requiredScore': 70,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'intermediate_2',
        'levelNumber': 7,
        'title': 'Intermediate 2',
        'description': 'Intermediate',
        'levelCategory': 'lesson',
        'isLocked': 1,
        'wordIds': '',
        'requiredScore': 70,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'intermediate_3',
        'levelNumber': 8,
        'title': 'Intermediate 3',
        'description': 'Intermediate',
        'levelCategory': 'lesson',
        'isLocked': 1,
        'wordIds': '',
        'requiredScore': 70,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'intermediate_test',
        'levelNumber': 9,
        'title': 'Intermediate test',
        'description': 'Intermediate',
        'levelCategory': 'test',
        'isLocked': 1,
        'wordIds': '',
        'requiredScore': 70,
        'createdAt': now,
        'updatedAt': now,
      },
      // Upper Intermediate (placeholder)
      {
        'id': 'upper_1',
        'levelNumber': 10,
        'title': 'Upper Intermediate 1',
        'description': 'Upper Intermediate',
        'levelCategory': 'lesson',
        'isLocked': 1,
        'wordIds': '',
        'requiredScore': 70,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'upper_2',
        'levelNumber': 11,
        'title': 'Upper Intermediate 2',
        'description': 'Upper Intermediate',
        'levelCategory': 'lesson',
        'isLocked': 1,
        'wordIds': '',
        'requiredScore': 70,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'upper_3',
        'levelNumber': 12,
        'title': 'Upper Intermediate 3',
        'description': 'Upper Intermediate',
        'levelCategory': 'lesson',
        'isLocked': 1,
        'wordIds': '',
        'requiredScore': 70,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'upper_test',
        'levelNumber': 13,
        'title': 'Upper Intermediate test',
        'description': 'Upper Intermediate',
        'levelCategory': 'test',
        'isLocked': 1,
        'wordIds': '',
        'requiredScore': 70,
        'createdAt': now,
        'updatedAt': now,
      },
      // Advanced (placeholder)
      {
        'id': 'advanced_1',
        'levelNumber': 14,
        'title': 'Advanced 1',
        'description': 'Advanced',
        'levelCategory': 'lesson',
        'isLocked': 1,
        'wordIds': '',
        'requiredScore': 70,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'advanced_2',
        'levelNumber': 15,
        'title': 'Advanced 2',
        'description': 'Advanced',
        'levelCategory': 'lesson',
        'isLocked': 1,
        'wordIds': '',
        'requiredScore': 70,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'advanced_3',
        'levelNumber': 16,
        'title': 'Advanced 3',
        'description': 'Advanced',
        'levelCategory': 'lesson',
        'isLocked': 1,
        'wordIds': '',
        'requiredScore': 70,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'advanced_test',
        'levelNumber': 17,
        'title': 'Advanced test',
        'description': 'Advanced',
        'levelCategory': 'test',
        'isLocked': 1,
        'wordIds': '',
        'requiredScore': 70,
        'createdAt': now,
        'updatedAt': now,
      },
      // Expert/Fluent (placeholder)
      {
        'id': 'expert_1',
        'levelNumber': 18,
        'title': 'Expert 1',
        'description': 'Expert',
        'levelCategory': 'lesson',
        'isLocked': 1,
        'wordIds': '',
        'requiredScore': 70,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'expert_2',
        'levelNumber': 19,
        'title': 'Expert 2',
        'description': 'Expert',
        'levelCategory': 'lesson',
        'isLocked': 1,
        'wordIds': '',
        'requiredScore': 70,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'expert_3',
        'levelNumber': 20,
        'title': 'Expert 3',
        'description': 'Expert',
        'levelCategory': 'lesson',
        'isLocked': 1,
        'wordIds': '',
        'requiredScore': 70,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'expert_test',
        'levelNumber': 21,
        'title': 'Expert test',
        'description': 'Expert',
        'levelCategory': 'test',
        'isLocked': 1,
        'wordIds': '',
        'requiredScore': 70,
        'createdAt': now,
        'updatedAt': now,
      },
    ];

    final words = [
      // Starter
      {
        'id': 'w1',
        'slovenian': 'Živjo',
        'english': 'Hello',
        'example': 'Živjo, kako si?',
        'difficulty': 1,
        'levelId': 'starter_1',
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'w2',
        'slovenian': 'Hvala',
        'english': 'Thank you',
        'example': 'Hvala za pomoč',
        'difficulty': 1,
        'levelId': 'starter_1',
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'w3',
        'slovenian': 'Prosim',
        'english': 'Please / You are welcome',
        'example': 'Prosim, vstopite.',
        'difficulty': 1,
        'levelId': 'starter_1',
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'w4',
        'slovenian': 'Ja',
        'english': 'Yes',
        'example': 'Ja, se strinjam.',
        'difficulty': 1,
        'levelId': 'starter_1',
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'w5',
        'slovenian': 'Ne',
        'english': 'No',
        'example': 'Ne, hvala.',
        'difficulty': 1,
        'levelId': 'starter_1',
        'createdAt': now,
        'updatedAt': now,
      },
      // Beginner 1
      {
        'id': 'w6',
        'slovenian': 'Dober dan',
        'english': 'Good day',
        'example': 'Dober dan, gospod.',
        'difficulty': 2,
        'levelId': 'beginner_1',
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'w7',
        'slovenian': 'Nasvidenje',
        'english': 'Goodbye',
        'example': 'Nasvidenje, se vidimo jutri.',
        'difficulty': 2,
        'levelId': 'beginner_1',
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'w8',
        'slovenian': 'Kako si?',
        'english': 'How are you?',
        'example': 'Hej, kako si danes?',
        'difficulty': 2,
        'levelId': 'beginner_1',
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'w9',
        'slovenian': 'Dobro jutro',
        'english': 'Good morning',
        'example': 'Dobro jutro vsem.',
        'difficulty': 2,
        'levelId': 'beginner_1',
        'createdAt': now,
        'updatedAt': now,
      },
      // Beginner 2
      {
        'id': 'w10',
        'slovenian': 'Mama',
        'english': 'Mom',
        'example': 'Moja mama kuha večerjo.',
        'difficulty': 2,
        'levelId': 'beginner_2',
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'w11',
        'slovenian': 'Oče',
        'english': 'Father',
        'example': 'Moj oče je učitelj.',
        'difficulty': 2,
        'levelId': 'beginner_2',
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'w12',
        'slovenian': 'Brat',
        'english': 'Brother',
        'example': 'Imam mlajšega brata.',
        'difficulty': 2,
        'levelId': 'beginner_2',
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'w13',
        'slovenian': 'Prijatelj',
        'english': 'Friend',
        'example': 'On je moj prijatelj.',
        'difficulty': 2,
        'levelId': 'beginner_2',
        'createdAt': now,
        'updatedAt': now,
      },
      // Beginner 3
      {
        'id': 'w14',
        'slovenian': 'Kruh',
        'english': 'Bread',
        'example': 'Kruh je svež.',
        'difficulty': 2,
        'levelId': 'beginner_3',
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'w15',
        'slovenian': 'Mleko',
        'english': 'Milk',
        'example': 'Pijem mleko vsak dan.',
        'difficulty': 2,
        'levelId': 'beginner_3',
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'w16',
        'slovenian': 'Čaj',
        'english': 'Tea',
        'example': 'Rad imam topel čaj.',
        'difficulty': 2,
        'levelId': 'beginner_3',
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'w17',
        'slovenian': 'Sladkor',
        'english': 'Sugar',
        'example': 'Prosim, manj sladkorja.',
        'difficulty': 2,
        'levelId': 'beginner_3',
        'createdAt': now,
        'updatedAt': now,
      },
    ];

    final lessonTasks = [
      // Starter
      {
        'id': 't1',
        'levelId': 'starter_1',
        'question': 'How do you say "Hello" in Slovenian?',
        'options': 'Živjo|Nasvidenje|Hvala|Prosim',
        'correctAnswer': 'Živjo',
        'kind': 'multipleChoice',
        'difficulty': 1,
        'explanation': 'Živjo is an informal hello/hi.',
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 't2',
        'levelId': 'starter_1',
        'question': 'What does "Prosim" mean?',
        'options': 'Please|Thank you|Goodbye|Yes',
        'correctAnswer': 'Please',
        'kind': 'multipleChoice',
        'difficulty': 1,
        'explanation': 'Prosim means "please" and also "you are welcome."',
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 't3',
        'levelId': 'starter_1',
        'question': '"Ne" means "No".',
        'options': 'True|False',
        'correctAnswer': 'True',
        'kind': 'trueFalse',
        'difficulty': 1,
        'explanation': 'Ne = No.',
        'createdAt': now,
        'updatedAt': now,
      },
      // Beginner 1
      {
        'id': 't4',
        'levelId': 'beginner_1',
        'question': 'Pick the correct translation for "Good morning".',
        'options': 'Dobro jutro|Nasvidenje|Prosim|Hvala',
        'correctAnswer': 'Dobro jutro',
        'kind': 'multipleChoice',
        'difficulty': 2,
        'explanation': 'Dobro jutro = Good morning.',
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 't5',
        'levelId': 'beginner_1',
        'question': 'Write the Slovenian for "How are you?".',
        'options': '',
        'correctAnswer': 'Kako si?',
        'kind': 'writeIn',
        'difficulty': 2,
        'explanation': 'Kako si? = How are you?',
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 't6',
        'levelId': 'beginner_1',
        'question': '"Nasvidenje" means goodbye.',
        'options': 'True|False',
        'correctAnswer': 'True',
        'kind': 'trueFalse',
        'difficulty': 1,
        'explanation': 'Nasvidenje = Goodbye.',
        'createdAt': now,
        'updatedAt': now,
      },
      // Beginner 2
      {
        'id': 't7',
        'levelId': 'beginner_2',
        'question': 'Select the correct option for "Father".',
        'options': 'Oče|Mama|Brat|Prijatelj',
        'correctAnswer': 'Oče',
        'kind': 'multipleChoice',
        'difficulty': 2,
        'explanation': 'Oče = Father.',
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 't8',
        'levelId': 'beginner_2',
        'question': 'Write the Slovenian for "Friend".',
        'options': '',
        'correctAnswer': 'Prijatelj',
        'kind': 'writeIn',
        'difficulty': 2,
        'explanation': 'Prijatelj = Friend.',
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 't9',
        'levelId': 'beginner_2',
        'question': 'True or false: "Brat" means sister.',
        'options': 'True|False',
        'correctAnswer': 'False',
        'kind': 'trueFalse',
        'difficulty': 2,
        'explanation': 'Brat = Brother, sestra = Sister.',
        'createdAt': now,
        'updatedAt': now,
      },
      // Beginner 3
      {
        'id': 't10',
        'levelId': 'beginner_3',
        'question': 'What does "mleko" mean?',
        'options': 'Milk|Bread|Tea|Sugar',
        'correctAnswer': 'Milk',
        'kind': 'multipleChoice',
        'difficulty': 2,
        'explanation': 'Mleko = Milk.',
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 't11',
        'levelId': 'beginner_3',
        'question': 'Write the Slovenian for "Sugar".',
        'options': '',
        'correctAnswer': 'Sladkor',
        'kind': 'writeIn',
        'difficulty': 2,
        'explanation': 'Sladkor = Sugar.',
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 't12',
        'levelId': 'beginner_3',
        'question': 'True or false: "Čaj" means tea.',
        'options': 'True|False',
        'correctAnswer': 'True',
        'kind': 'trueFalse',
        'difficulty': 2,
        'explanation': 'Čaj = Tea.',
        'createdAt': now,
        'updatedAt': now,
      },
      // Beginner Test
      {
        'id': 't13',
        'levelId': 'beginner_test',
        'question': 'Translate to English: "Nasvidenje".',
        'options': '',
        'correctAnswer': 'Goodbye',
        'kind': 'writeIn',
        'difficulty': 2,
        'explanation': 'Nasvidenje = Goodbye.',
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 't14',
        'levelId': 'beginner_test',
        'question': 'Choose the correct option for "Kruh".',
        'options': 'Bread|Tea|Milk|Coffee',
        'correctAnswer': 'Bread',
        'kind': 'multipleChoice',
        'difficulty': 2,
        'explanation': 'Kruh = Bread.',
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 't15',
        'levelId': 'beginner_test',
        'question': 'True or false: "Prijatelj" means friend.',
        'options': 'True|False',
        'correctAnswer': 'True',
        'kind': 'trueFalse',
        'difficulty': 2,
        'explanation': 'Prijatelj = Friend.',
        'createdAt': now,
        'updatedAt': now,
      },
    ];

    final batch = txn.batch();
    for (final level in levels) {
      batch.insert('levels', level, conflictAlgorithm: ConflictAlgorithm.replace);
    }
    for (final word in words) {
      batch.insert('words', word, conflictAlgorithm: ConflictAlgorithm.replace);
    }
    for (final task in lessonTasks) {
      batch.insert('lesson_tasks', task, conflictAlgorithm: ConflictAlgorithm.replace);
    }
    await batch.commit(noResult: true);
  });
}
